const CACHE = 'ttd-hq-v8';
const CORE = [
  './',
  './arcade.html',
  './captain-calorie.html',
  './comics.html',
  './dossiers.html',
  './financial-district.html',
  './grim-ledger.html',
  './hardcase-87.html',
  './index.html',
  './issue-1.html',
  './issue-2.html',
  './issue-3.html',
  './map.html',
  './military-district.html',
  './nikki-nitro.html',
  './nutrition-district.html',
  './payments.html',
  './store.html',
  './tbn.html',
  './titan-heights.html',
  './titan-spire.html',
  './vexxa-blaze.html',
  './vhs-quarter.html',
  './viper.html',
  './styles.css',
  './app.js',
  './manifest.json',
  './assets/images/ttd-banner.png',
  './assets/images/ttd-logo-app.png'
];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE))));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k))))));
self.addEventListener('fetch',e=>e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request))));
