(() => {
'use strict';
const canvas=document.getElementById('tb94Canvas'); if(!canvas)return;
const ctx=canvas.getContext('2d',{alpha:false}); ctx.imageSmoothingEnabled=false;
const W=960,H=540,FIELD={left:90,right:890,top:118,bottom:485},TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),lerp=(a,b,t)=>a+(b-a)*t,pad=n=>Math.floor(Math.max(0,n)).toString().padStart(6,'0');
const C={g:'#8aff2b',p:'#ff2d95',b:'#39d7ff',y:'#ffe53b',w:'#fff',k:'#050609'};
const ROSTER=[
{id:'dex',name:'DEX VOLT',no:7,color:C.g,accent:C.p,speed:235,power:1.1,hp:100,size:25,special:'VOLTAGE STORM'},
{id:'nikki',name:'NIKKI NITRO',no:87,color:C.p,accent:C.b,speed:282,power:.84,hp:86,size:21,special:'NITRO BREAK'},
{id:'mack',name:'MACK MAUL',no:99,color:C.y,accent:C.g,speed:190,power:1.55,hp:138,size:31,special:'EARTHQUAKE'}];
const DIFF={
casual:{label:'CASUAL',quarter:75,enemySpeed:.82,spawn:1.18,damage:.70,oppTD:.28,oppFG:.13,pickup:.82,clockLoss:[6,11]},
hard:{label:'HARD',quarter:75,enemySpeed:1.04,spawn:.94,damage:1.00,oppTD:.42,oppFG:.14,pickup:1.00,clockLoss:[8,14]},
titan:{label:'TITAN',quarter:75,enemySpeed:1.26,spawn:.72,damage:1.28,oppTD:.58,oppFG:.15,pickup:1.30,clockLoss:[10,17]}};
let difficulty=localStorage.getItem('ttd-tb94-diff')||'hard';
const UI={you:$('#tb94You'),them:$('#tb94Them'),quarter:$('#tb94Quarter'),clock:$('#tb94Clock'),down:$('#tb94Down'),field:$('#tb94Field'),hp:$('#tb94Hp'),meter:$('#tb94Meter'),up:$('#tb94Up'),left:$('#tb94Left'),right:$('#tb94Right'),downBtn:$('#tb94DownBtn'),center:$('#tb94Center'),smash:$('#tb94Smash'),dash:$('#tb94Dash'),special:$('#tb94Special')};
function $(s){return document.querySelector(s)}
const ASSETS={},files={arena:'assets/images/titanball94/stadium3.PNG',grass:'assets/images/titanball94/tb94-grass.PNG',field:'assets/images/titanball94/tb94-field-overlay.PNG',dex:'assets/images/titanball94/dex-sheet.PNG',nikki:'assets/images/titanball94/nikki-sheet.PNG',mack:'assets/images/titanball94/bruiser-sheet.PNG',bobby:'assets/images/titanball94/bobby94.PNG',juice:'assets/images/titanball94/sjuice94.PNG',loops:'assets/images/titanball94/loops94.PNG',td:'assets/images/titanball94/touchdown94.PNG',fd:'assets/images/titanball94/firstdown94.PNG',go:'assets/images/titanball94/Gameover94.PNG',fx:'assets/images/titanball94/effex.PNG'};
for(const[k,v]of Object.entries(files)){let im=new Image();im.src=v;ASSETS[k]=im}
const ready=k=>ASSETS[k]?.complete&&ASSETS[k].naturalWidth>0;
const POSE={dex:{run:[1000,48,500,410],idle:[438,22,235,455],portrait:[0,0,410,500]},nikki:{run:[1000,48,485,420],idle:[425,20,235,460],portrait:[0,0,410,500]},mack:{run:[920,22,555,400],idle:[520,15,350,500],portrait:[0,0,470,510]},enemy:[920,22,555,400]};
let audio=null;function tone(f=220,d=.06,type='square',g=.02){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),ga=audio.createGain();o.type=type;o.frequency.value=f;ga.gain.value=g;ga.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(ga);ga.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
const state={mode:'boot',select:0,paused:false,time:0,last:performance.now(),you:0,them:0,q:1,clock:75,sudden:false,score:0,fieldYards:0,totalYards:0,seriesStart:0,down:1,toGo:20,drive:1,hp:100,meter:0,banner:'',bannerTime:0,goTime:0,spawnTimer:.8,pickupTimer:4,defenders:[],pickups:[],particles:[],shake:0,flash:0,world:0,mult:1,combo:0,resetTimer:0,oppTimer:0,oppText:'',splash:'',splashTime:0,locked:false};
const p={x:210,y:300,vx:0,vy:0,r:25,smash:0,dash:0,inv:0,special:0,trail:[]};
const input={up:false,down:false,left:false,right:false};
const current=()=>ROSTER[state.select],cfg=()=>DIFF[difficulty];

function resetPlayer(fullHP=false){const c=current();p.x=210;p.y=(FIELD.top+FIELD.bottom)/2;p.vx=p.vy=0;p.r=c.size;p.smash=p.dash=p.inv=p.special=0;p.trail=[];if(fullHP)state.hp=c.hp;else state.hp=Math.min(c.hp,Math.max(state.hp,Math.ceil(c.hp*.45)))}
function resetSeries(){state.fieldYards=0;state.seriesStart=0;state.down=1;state.toGo=20;state.defenders=[];state.pickups=[];resetPlayer(true)}
function newMatch(){state.mode='playing';state.locked=true;state.you=0;state.them=0;state.q=1;state.clock=cfg().quarter;state.sudden=false;state.score=0;state.totalYards=0;state.drive=1;state.meter=0;state.mult=1;state.combo=0;resetSeries();kickoff(`Q1 // ${cfg().label}`)}
function kickoff(label='OFFENSE'){state.banner=label;state.bannerTime=1.3;state.goTime=1.4;state.spawnTimer=.9;state.pickupTimer=3.2;state.defenders=[];state.pickups=[];tone(196,.07);setTimeout(()=>tone(294,.07),80);setTimeout(()=>tone(440,.11),160)}
function nextQuarter(){if(state.q<4){state.q++;state.clock=cfg().quarter;resetSeries();state.mode='quarter';state.oppTimer=2.2;state.oppText=state.q===3?'HALFTIME OVER // Q3':'QUARTER OVER // Q'+state.q;return} if(state.you===state.them){state.sudden=true;state.mode='quarter';state.oppTimer=2.5;state.oppText='SUDDEN DEATH // NEXT SCORE WINS';resetSeries();return} finishMatch()}
function finishMatch(){state.mode=state.you>state.them?'victory':'defeat';state.banner=state.mode==='victory'?'TITAN BALL CHAMPIONS':'FINAL WHISTLE // DEFEAT';state.bannerTime=99;localStorage.setItem('ttd-tb94-high',String(Math.max(Number(localStorage.getItem('ttd-tb94-high')||0),Math.floor(state.score))))}
function clockAdvance(sec){if(state.sudden)return;state.clock=Math.max(0,state.clock-sec);if(state.clock<=0&&state.mode==='playing'){state.mode='quarter';state.oppTimer=1.8;state.oppText='QUARTER EXPIRED'}}
function possessionOver(reason){state.mode='opponent';state.oppTimer=2.5;state.oppText=reason;state.defenders=[];state.pickups=[]}
function opponentPossession(){
 const d=cfg(),r=Math.random();let pts=0,label='DEFENCE HOLDS // PUNT';
 if(r<d.oppTD){pts=7;label='THEM // TOUCHDOWN +7'} else if(r<d.oppTD+d.oppFG){pts=3;label='THEM // MUTANT FIELD GOAL +3'}
 state.them+=pts;clockAdvance(Math.floor(rand(...d.clockLoss)));
 if(state.sudden&&pts>0){finishMatch();return}
 state.drive++;resetSeries();
 if(state.clock<=0&&!state.sudden){nextQuarter();return}
 state.mode='playing';kickoff(`${label} // YOUR BALL`);
}
function touchdown(){state.you+=7;state.score+=7500*state.mult;state.meter=clamp(state.meter+40,0,100);state.splash='td';state.splashTime=1.35;state.flash=.35;state.shake=12;tone(523,.08);setTimeout(()=>tone(659,.08),80);setTimeout(()=>tone(784,.15),160);if(state.sudden){finishMatch();return}clockAdvance(8);possessionOver('TOUCHDOWN // +7')}
function firstDown(){state.seriesStart=state.fieldYards;state.down=1;state.toGo=20;state.score+=1200;state.splash='fd';state.splashTime=.9;state.banner='FIRST DOWN!';state.bannerTime=.7;tone(520,.07)}
function endDown(reason='TACKLED'){
 state.defenders=[];state.pickups=[];state.down++;state.toGo=Math.max(1,20-(state.fieldYards-state.seriesStart));clockAdvance(5);
 if(state.clock<=0&&!state.sudden){nextQuarter();return}
 if(state.down>4){possessionOver('TURNOVER ON DOWNS');return}
 resetPlayer(false);state.banner=`${reason} // DOWN ${state.down}`;state.bannerTime=.8;state.goTime=.7
}
function playerDestroyed(){state.hp=0;state.flash=.35;state.shake=14;possessionOver('PLAYER DESTROYED // TURNOVER')}
function spawnDef(){const d=cfg(),drive=state.drive,r=Math.random();let type=r>.62?'speed':'bruiser';if(drive>1&&r>.91)type='ref';let base=type==='speed'?{r:21,s:170,hp:1,p:.86}:{r:27,s:125,hp:2,p:1.2};if(type==='ref')base={r:19,s:112,hp:1,p:.65};state.defenders.push({type,x:W+45,y:rand(FIELD.top+40,FIELD.bottom-40),r:base.r,s:base.s*d.enemySpeed+drive*5,hp:base.hp,power:base.p,dead:false,phase:rand(0,6.2)})}
function spawnPickup(){let type=Math.random()<.42?'juice':'loops';state.pickups.push({type,x:W+30,y:rand(FIELD.top+35,FIELD.bottom-35),r:17,spin:0})}
function hit(a,b){let dx=a.x-b.x,dy=a.y-b.y,rr=a.r+b.r;return dx*dx+dy*dy<rr*rr}
function burst(x,y,c,n=12){for(let i=0;i<n;i++)state.particles.push({x,y,vx:rand(-210,210),vy:rand(-210,210),life:rand(.25,.7),c,s:rand(2,7)})}
function ko(d){d.dead=true;state.score+=d.type==='ref'?900:500;state.meter=clamp(state.meter+(d.type==='ref'?18:10),0,100);state.mult=clamp(state.mult+.1,1,4);state.combo=2.5;state.shake=6;burst(d.x,d.y,d.type==='ref'?C.y:C.p,14);tone(78,.05,'sawtooth',.025)}
function tackle(d){if(p.inv>0||p.special>0){ko(d);return}const c=current(),dmg=Math.round(19*d.power/c.power*cfg().damage);state.hp-=dmg;p.inv=.85;d.dead=true;state.flash=.16;state.shake=10;burst(p.x,p.y,C.p,15);if(state.hp<=0){playerDestroyed();return}endDown(`HIT -${dmg}HP`)}
function smash(){if(state.mode!=='playing')return advance();if(state.goTime>0||p.smash>0)return;p.smash=.28;state.shake=4;tone(92,.05,'square',.028)}
function dash(){if(state.mode!=='playing')return advance();if(state.goTime>0||p.dash>0)return;p.dash=.32;p.inv=Math.max(p.inv,.16);tone(285,.04,'square',.018)}
function special(){if(state.mode!=='playing')return advance();if(state.goTime>0||state.meter<100||p.special>0)return;state.meter=0;p.special=current().id==='nikki'?4.5:4;p.inv=1;state.banner=current().special;state.bannerTime=1.1;state.flash=.25;state.shake=8;if(current().id==='mack')for(const d of state.defenders){d.dead=true;state.score+=400}tone(430,.1,'sawtooth',.03);setTimeout(()=>tone(760,.13,'square',.028),100)}
function advance(){if(state.mode==='boot')state.mode='select';else if(state.mode==='select')state.mode='difficulty';else if(state.mode==='difficulty')newMatch();else if(state.mode==='victory'||state.mode==='defeat'){state.locked=false;state.mode='select'}}

document.querySelectorAll('.tb94-diff').forEach(b=>{b.classList.toggle('active',b.dataset.diff===difficulty);b.addEventListener('pointerdown',e=>{e.preventDefault();if(state.locked)return;difficulty=b.dataset.diff;localStorage.setItem('ttd-tb94-diff',difficulty);document.querySelectorAll('.tb94-diff').forEach(x=>x.classList.toggle('active',x===b));if(state.mode==='difficulty')tone(300,.05)})});
function hold(el,key){const off=()=>{input[key]=false;el?.classList.remove('active')};el?.addEventListener('pointerdown',e=>{e.preventDefault();input[key]=true;el.classList.add('active')});['pointerup','pointercancel','pointerleave'].forEach(v=>el?.addEventListener(v,off))}
hold(UI.up,'up');hold(UI.downBtn,'down');hold(UI.left,'left');hold(UI.right,'right');UI.center?.addEventListener('pointerdown',()=>{input.up=input.down=input.left=input.right=false});
for(const[el,fn]of[[UI.smash,smash],[UI.dash,dash],[UI.special,special]])el?.addEventListener('pointerdown',e=>{e.preventDefault();fn()});
canvas.addEventListener('pointerdown',e=>{if(state.mode==='select'){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;if(y>115&&y<460){let i=Math.floor((x-70)/283);if(i>=0&&i<3){if(state.select===i)state.mode='difficulty';else state.select=i;return}}}advance()});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(state.mode==='select'){if(e.code==='ArrowLeft'||e.code==='KeyA')state.select=(state.select+2)%3;if(e.code==='ArrowRight'||e.code==='KeyD')state.select=(state.select+1)%3;if(e.code==='Enter'||e.code==='Space')state.mode='difficulty';return}if(state.mode==='difficulty'){if(e.code==='Digit1')difficulty='casual';if(e.code==='Digit2')difficulty='hard';if(e.code==='Digit3')difficulty='titan';if(e.code==='Enter'||e.code==='Space')newMatch();return}if(state.mode!=='playing'){if(e.code==='Enter'||e.code==='Space')advance();return}if(e.code==='ArrowUp'||e.code==='KeyW')input.up=true;if(e.code==='ArrowDown'||e.code==='KeyS')input.down=true;if(e.code==='ArrowLeft'||e.code==='KeyA')input.left=true;if(e.code==='ArrowRight'||e.code==='KeyD')input.right=true;if(e.code==='KeyX')smash();if(e.code==='KeyC'||e.code==='Space')dash();if(e.code==='KeyV')special();if(e.code==='KeyP')state.paused=!state.paused});
window.addEventListener('keyup',e=>{if(e.code==='ArrowUp'||e.code==='KeyW')input.up=false;if(e.code==='ArrowDown'||e.code==='KeyS')input.down=false;if(e.code==='ArrowLeft'||e.code==='KeyA')input.left=false;if(e.code==='ArrowRight'||e.code==='KeyD')input.right=false});

function update(dt){
 state.time+=dt;state.bannerTime=Math.max(0,state.bannerTime-dt);state.flash=Math.max(0,state.flash-dt);state.shake=Math.max(0,state.shake-dt*45);state.splashTime=Math.max(0,state.splashTime-dt);
 if(state.mode==='quarter'){state.oppTimer-=dt;if(state.oppTimer<=0){if(state.oppText==='QUARTER EXPIRED')nextQuarter();else{state.mode='playing';kickoff(state.oppText)}}return}
 if(state.mode==='opponent'){state.oppTimer-=dt;if(state.oppTimer<=0)opponentPossession();return}
 if(state.mode!=='playing'||state.paused)return;
 if(state.goTime>0){state.goTime-=dt;return}
 if(!state.sudden){state.clock=Math.max(0,state.clock-dt);if(state.clock<=0){state.mode='quarter';state.oppTimer=1.8;state.oppText='QUARTER EXPIRED';return}}
 p.smash=Math.max(0,p.smash-dt);p.dash=Math.max(0,p.dash-dt);p.inv=Math.max(0,p.inv-dt);p.special=Math.max(0,p.special-dt);if(state.combo>0){state.combo-=dt;if(state.combo<=0)state.mult=1}
 const c=current();let sp=c.speed*(p.dash>0?1.82:1);if(p.special>0&&c.id==='nikki')sp*=1.6;let dx=(input.right?1:0)-(input.left?1:0),dy=(input.down?1:0)-(input.up?1:0),l=Math.hypot(dx,dy)||1;dx/=l;dy/=l;p.vx=lerp(p.vx,dx*sp,.22);p.vy=lerp(p.vy,dy*sp,.22);if(!dx)p.vx*=.78;if(!dy)p.vy*=.78;p.x=clamp(p.x+p.vx*dt,FIELD.left+20,FIELD.right-20);p.y=clamp(p.y+p.vy*dt,FIELD.top+20,FIELD.bottom-20);
 const f=Math.max(0,p.vx)*dt/70+(p.dash>0?4.2:1.55)*dt;state.fieldYards+=f;state.totalYards+=f;state.score+=f*35*state.mult;state.world=(state.world+f*13)%80;if(state.fieldYards>=100){state.fieldYards=100;touchdown();return}
 if(state.fieldYards-state.seriesStart>=20){firstDown()}
 state.spawnTimer-=dt;if(state.spawnTimer<=0){spawnDef();state.spawnTimer=rand(.55,1.0)*cfg().spawn}
 state.pickupTimer-=dt;if(state.pickupTimer<=0){spawnPickup();state.pickupTimer=rand(3.8,6.8)*cfg().pickup}
 for(const d of state.defenders){if(d.dead)continue;d.phase+=dt*4;let tx=p.x+(d.type==='speed'?35:0),ty=p.y+Math.sin(d.phase)*10,vx=tx-d.x,vy=ty-d.y,dl=Math.hypot(vx,vy)||1;d.x+=(vx/dl)*d.s*dt;d.y+=(vy/dl)*d.s*.84*dt;if(hit(p,d)){if(p.smash>0||p.special>0){d.hp-=Math.ceil(c.power*(p.special>0?1.5:1.2));if(d.hp<=0)ko(d);else d.x+=55}else tackle(d)}}
 for(const a of state.pickups){a.x-=45*dt;a.spin+=dt*6;if(hit(p,a)){a.x=-999;if(a.type==='juice'){state.hp=clamp(state.hp+25,0,c.hp);state.meter=clamp(state.meter+25,0,100);state.score+=700}else{state.meter=clamp(state.meter+45,0,100);state.score+=1200;p.dash=Math.max(p.dash,1.0)}burst(p.x,p.y,a.type==='juice'?C.g:C.p,12);tone(660,.05)}}
 for(const a of state.particles){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vx*=.97;a.vy*=.97}
 state.defenders=state.defenders.filter(d=>!d.dead&&d.x>-90);state.pickups=state.pickups.filter(a=>a.x>-70);state.particles=state.particles.filter(a=>a.life>0);
 sync();
}

function sync(){UI.you.textContent=state.you;UI.them.textContent=state.them;UI.quarter.textContent=state.sudden?'OT':`Q${state.q}`;let s=Math.max(0,Math.ceil(state.clock)),m=Math.floor(s/60),ss=String(s%60).padStart(2,'0');UI.clock.textContent=state.sudden?'SD':`${m}:${ss}`;UI.down.textContent=`${state.down} & ${Math.ceil(state.toGo)}`;UI.field.textContent=`${Math.floor(state.fieldYards)} YD`;UI.hp.textContent=Math.max(0,Math.ceil(state.hp));UI.meter.textContent=`${Math.floor(state.meter)}%`;UI.special.classList.toggle('ready',state.meter>=100);UI.special.textContent=state.meter>=100?`⚡ ${current().special}`:`⚡ MUTATION ${Math.floor(state.meter)}%`}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}function txt(t,x,y,s=22,c='#fff',a='left'){ctx.fillStyle=c;ctx.font=`900 ${s}px "Barlow Condensed",Impact,sans-serif`;ctx.textAlign=a;ctx.textBaseline='middle';ctx.fillText(t,x,y)}function shadow(t,x,y,s,c,a='left'){txt(t,x+3,y+3,s,'rgba(0,0,0,.8)',a);txt(t,x,y,s,c,a)}
function sheet(k,pose,x,y,w,h,flip=false){if(!ready(k))return false;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(ASSETS[k],...pose,0,0,w,h)}else ctx.drawImage(ASSETS[k],...pose,x,y,w,h);ctx.restore();return true}
function drawField(){if(ready('arena'))ctx.drawImage(ASSETS.arena,0,0,W,H);else rect(0,0,W,H,'#073516');if(ready('grass')){ctx.save();ctx.globalAlpha=.52;let off=state.world%360;for(let x=-360-off;x<W+360;x+=360)ctx.drawImage(ASSETS.grass,x,62,360,H-84);ctx.restore()}if(ready('field')){ctx.save();ctx.globalAlpha=.9;ctx.drawImage(ASSETS.field,0,48,W,H-64);ctx.restore()}ctx.strokeStyle='rgba(255,229,59,.85)';ctx.lineWidth=3;let first=clamp(FIELD.left+((state.seriesStart+20-state.fieldYards)/20)*150+300,FIELD.left,FIELD.right);ctx.beginPath();ctx.moveTo(first,FIELD.top);ctx.lineTo(first,FIELD.bottom);ctx.stroke()}
function drawPlayer(){const c=current();if(p.inv>0&&Math.floor(state.time*14)%2===0)return;ctx.save();ctx.globalAlpha=.3;ctx.fillStyle='#000';ctx.beginPath();ctx.ellipse(p.x,p.y+31,p.r*1.45,p.r*.5,0,0,TAU);ctx.fill();ctx.restore();if(p.special>0){ctx.strokeStyle=c.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,p.r+14+Math.sin(state.time*15)*4,0,TAU);ctx.stroke()}let moving=Math.hypot(p.vx,p.vy)>22||p.dash>0,key=c.id==='mack'?'mack':c.id,pose=POSE[c.id][moving?'run':'idle'],w=(moving?126:92)*(c.id==='mack'?1.12:1),h=(moving?112:132)*(c.id==='mack'?1.12:1);if(!sheet(key,pose,p.x-w/2,p.y-h/2,w,h,p.vx<0)){ctx.fillStyle=c.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()}}
function drawDef(d){if(d.type==='ref'&&ready('bobby')){ctx.drawImage(ASSETS.bobby,d.x-34,d.y-52,68,104);return}let w=d.type==='speed'?78:100,h=d.type==='speed'?82:104;if(!sheet('mack',POSE.enemy,d.x-w/2,d.y-h/2,w,h,true)){ctx.fillStyle=d.type==='speed'?C.b:C.p;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,TAU);ctx.fill()}}
function drawPickup(a){let y=a.y+Math.sin(a.spin)*5,k=a.type==='juice'?'juice':'loops';if(ready(k))ctx.drawImage(ASSETS[k],a.x-25,y-30,50,60);else rect(a.x-12,y-15,24,30,a.type==='juice'?C.g:C.p)}
function drawEffects(){for(const a of state.particles){ctx.globalAlpha=clamp(a.life/.7,0,1);rect(a.x,a.y,a.s,a.s,a.c)}ctx.globalAlpha=1}
function scorebar(){rect(14,12,932,82,'rgba(3,5,7,.90)');let c=current();shadow(`${c.name} #${c.no}`,28,35,22,c.color);txt(`${cfg().label}`,28,63,14,C.y);shadow(`YOU ${state.you}`,420,33,31,C.g,'right');shadow(`${state.sudden?'OT':'Q'+state.q} ${state.sudden?'SUDDEN DEATH':UI.clock.textContent}`,W/2,64,18,'#fff','center');shadow(`THEM ${state.them}`,540,33,31,C.p);shadow(`DOWN ${state.down} // ${Math.ceil(state.toGo)} TO GO`,930,61,18,C.g,'right');shadow(`SCORE ${pad(state.score)}`,930,31,21,'#fff','right');if(state.mult>1)shadow(`CROWD RAGE x${state.mult.toFixed(1)}`,W/2,106,19,C.p,'center');if(state.bannerTime>0){rect(220,100,520,52,'rgba(0,0,0,.82)');shadow(state.banner,W/2,127,28,state.banner.includes('FIRST')?C.y:'#fff','center')}}
function overlay(title,sub='',color='#fff'){rect(0,0,W,H,'rgba(0,0,0,.70)');shadow(title,W/2,220,58,color,'center');if(sub)txt(sub,W/2,285,23,'#fff','center')}
function drawBoot(){drawField();overlay("TITAN BALL '94","V6 // FULL MATCH ENGINE",C.p);txt('FOUR QUARTERS // ONE WINNER',W/2,336,22,C.g,'center');if(Math.floor(state.time*2)%2===0)shadow('PRESS START',W/2,430,30,C.y,'center')}
function drawSelect(){drawField();rect(0,0,W,H,'rgba(0,0,0,.68)');shadow('CHOOSE YOUR MUTANT',W/2,60,46,'#fff','center');ROSTER.forEach((c,i)=>{let x=72+i*283,sel=i===state.select;rect(x,112,250,350,sel?'rgba(10,22,15,.95)':'rgba(4,5,7,.85)');ctx.strokeStyle=sel?c.color:'rgba(255,255,255,.16)';ctx.lineWidth=sel?4:1;ctx.strokeRect(x,112,250,350);let key=c.id==='mack'?'mack':c.id;sheet(key,POSE[c.id].portrait,x+34,130,182,150);shadow(c.name,x+125,314,26,c.color,'center');txt(`#${c.no}`,x+125,345,28,'#fff','center');txt(c.special,x+125,390,16,C.y,'center');if(sel)txt('SELECTED',x+125,435,15,C.g,'center')});txt('TAP SELECTED CARD AGAIN // ENTER CONFIRM',W/2,500,17,'#aaa','center')}
function drawDifficulty(){drawField();rect(0,0,W,H,'rgba(0,0,0,.72)');shadow('SELECT DIFFICULTY',W/2,92,47,'#fff','center');let arr=['casual','hard','titan'];arr.forEach((k,i)=>{let y=160+i*92,active=k===difficulty,d=DIFF[k];rect(230,y,500,70,active?'rgba(138,255,43,.15)':'rgba(255,255,255,.04)');ctx.strokeStyle=active?C.g:'rgba(255,255,255,.15)';ctx.strokeRect(230,y,500,70);shadow(d.label,W/2,y+27,28,active?C.g:'#fff','center');txt(k==='casual'?'COMPLETABLE // FRIENDLY DEFENCE':k==='hard'?'PROPER FIGHT // OPPONENT CAN WIN':'EXTREME // DEFENCE WANTS BLOOD',W/2,y+53,14,active?'#fff':'#999','center')});txt('BUTTONS BELOW OR 1 / 2 / 3 // ENTER KICKOFF',W/2,475,16,C.y,'center')}
function drawOpponent(){drawField();overlay('DEFENCE ON THE FIELD',state.oppText,C.p);txt(`YOU ${state.you}  //  THEM ${state.them}`,W/2,340,28,'#fff','center')}
function drawQuarter(){drawField();overlay(state.oppText, state.q<4&&!state.sudden?`SCORE ${state.you} - ${state.them}`:'',C.y)}
function drawEnd(win){drawField();rect(0,0,W,H,'rgba(0,0,0,.72)');shadow(win?'TITAN BALL CHAMPIONS':'FINAL WHISTLE',W/2,150,60,win?C.g:C.p,'center');shadow(`${state.you}  -  ${state.them}`,W/2,245,72,'#fff','center');txt(`${current().name} // ${Math.floor(state.totalYards)} YARDS // SCORE ${pad(state.score)}`,W/2,330,20,C.y,'center');txt(win?'THE CITY SURVIVES. THE OPPOSITION DOES NOT.':'MEDIC. AMMO. APPEAL DENIED.',W/2,380,19,'#fff','center');shadow('PRESS START // PLAY AGAIN',W/2,465,23,C.g,'center')}
function render(){let sx=state.shake>0?rand(-state.shake,state.shake):0,sy=state.shake>0?rand(-state.shake*.5,state.shake*.5):0;ctx.save();ctx.translate(sx,sy);if(state.mode==='boot')drawBoot();else if(state.mode==='select')drawSelect();else if(state.mode==='difficulty')drawDifficulty();else if(state.mode==='opponent')drawOpponent();else if(state.mode==='quarter')drawQuarter();else if(state.mode==='victory')drawEnd(true);else if(state.mode==='defeat')drawEnd(false);else{drawField();for(const a of state.pickups)drawPickup(a);for(const d of state.defenders)drawDef(d);drawPlayer();drawEffects();scorebar();if(state.goTime>0){let word=state.goTime>.75?'READY':'GO!';shadow(word,W/2,H/2,word==='GO!'?95:55,word==='GO!'?C.g:C.y,'center')}if(state.splashTime>0){let k=state.splash==='td'?'td':'fd';if(ready(k)){ctx.globalAlpha=.95;ctx.drawImage(ASSETS[k],230,120,500,290);ctx.globalAlpha=1}}if(state.paused)overlay('PAUSED','PRESS P',C.y)}ctx.globalAlpha=.08;for(let y=0;y<H;y+=4)rect(0,y,W,1,'#000');ctx.globalAlpha=1;if(state.flash>0){ctx.globalAlpha=clamp(state.flash*2,0,.5);rect(0,0,W,H,'#fff');ctx.globalAlpha=1}ctx.restore()}
function loop(now){let dt=Math.min(.033,(now-state.last)/1000||0);state.last=now;update(dt);sync();render();requestAnimationFrame(loop)}
sync();requestAnimationFrame(loop);
})();